### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by cursorweb** [cursorweb/Redirector-Extension#2]
- [ ] Rearrange blacklist/redirect
- [x] Make blacklist/redirect easier to use (https://youtube.com)
- [x] Easily configure current page (blacklist/redirect)
- [ ] Prompt reload instead of force reload
- [ ] Make prompts and dialog look prettier
- [ ] Add confirm leave if unsaved changes
- [ ] Make all changes auto-saved (and then remove all save btns)
- [x] Bug: Changing the redirect status from `disabled` to `enabled` will not have existing distracting websites redirect.
- [ ] Efficiency: Reload only bad websites

**Comment by cursorweb** [comment]
Implement in firefox?
